# Welcome to Jekyll!
#

# Site settings
title: Centrix
description: |
  The House of fine 
  Accesories and CLothing  
  for Men and Women
owner: Centrix Inc # or company name
first_published: 2016 # if migrating another site, the year of your first publish
email: centrix2016@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/centrix2016
  github: https://github.com/centrix2016
  linkedin-square: https://linkedin.com/in/centrix2016
  facebook-official: https://facebook.com/centrix2016
  google-plus-square: https://plus.google.com/u/0/+centrix2016
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
